version: '2'
services:
    configuration-database-tool:
        image: byuoitav/configuration-database-tool:stage
        ports:
            - "9900:9900"
        environment:
            - DB_ADDRESS=$DB_ADDRESS
            - DB_USERNAME=$DB_USERNAME
            - DB_PASSWORD=$DB_PASSWORD
            - LDAP_USERNAME=$LDAP_USERNAME
            - LDAP_PASSWORD=$LDAP_PASSWORD
            - LDAP_SEARCH_SCOPE=$LDAP_SEARCH_SCOPE
            - JWT_SIGNING_TOKEN=$JWT_SIGNING_TOKEN
            - LDAP_URL=$LDAP_URL
            - BYPASS_AUTH=$BYPASS_AUTH
            - ENDPOINT_ACCESS_KEY=$ENDPOINT_ACCESS_KEY
            - ENDPOINT_USERNAME=$ENDPOINT_USERNAME
            - HUB_ADDRESS=$HUB_ADDRESS
        network_mode: "host"
        restart: always
        tty: true
        logging: 
            options:
                max-size: "100m"