version: '2'
services:
    configuration-database-tool:
        image: byuoitav/configuration-database-tool:master
        ports:
            - "9999:9999"
        environment:
            - DB_ADDRESS=$DB_ADDRESS
            - DB_USERNAME=$DB_USERNAME
            - DB_PASSWORD=$DB_PASSWORD
            - LDAP_USERNAME=$LDAP_USERNAME
            - LDAP_PASSWORD=$LDAP_PASSWORD
            - LDAP_SEARCH_SCOPE=$LDAP_SEARCH_SCOPE
            - JWT_SIGNING_TOKEN=$JWT_SIGNING_TOKEN
            - LDAP_URL=$LDAP_URL
        network_mode: "host"
        restart: always
        tty: true
        logging: 
            options:
                max-size: "100m"